routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
 * Admin Route
*/

Route::prefix('admin')->group(function () {
    Route::middleware('auth:admin')->group(function () {
        //dashboard route
        Route::get('/', 'dashboardController@index');

        //Product route
        Route::resource('/product', 'ProductController');

        //Billings route
        Route::resource('/billings', 'BillingController');
        Route::get('/confirm/{id}', 'BillingController@confirm')->name('orders.confirm');
        Route::get('/pending/{id}', 'BillingController@pending')->name('orders.pending');
        //Category route
        Route::resource('/category', 'CategoryController');

        //Color route
        Route::resource('/color', 'ColorController');

        //Size route
        Route::resource('/size', 'SizeController');

        //feedbacks route
        Route::resource('/feedbacks', 'FeedbackController');


        //Order route
        Route::resource('/orders', 'OrderController');
        Route::get('/confirm/{id}', 'OrderController@confirm')->name('orders.confirm');
        Route::get('/pending/{id}', 'OrderController@pending')->name('orders.pending');

        //User route
        Route::resource('/users', 'UserController');
        Route::get('/active/{id}', 'UserController@active')->name('users.active');
        Route::get('/block/{id}', 'UserController@block')->name('users.block');

        //logout Route
        Route::get('/logout', 'AdminUserController@logout');
    });
    //Admin route
    Route::resource('/login', 'AdminUserController');
});

/* Front-end Route */

//Home Route
Route::resource('/', 'front\HomeController');

//User Rgestrition Route
Route::get('/user/register', 'front\RegisterController@index');
Route::post('/user/register', 'front\RegisterController@store');

//User Login Route
Route::get('/user/login', 'front\SessionController@index');
Route::post('/user/login', 'front\SessionController@store');
Route::get('/logout', 'front\SessionController@logout');


//User Profile Route
Route::get('/user/profile', 'front\UserProfileController@index');
Route::get('/user/order/{id}', 'front\UserProfileController@show');

//Product Profile Route
Route::get('/product/{id}', 'front\ProductController@index');

//Cart Route
Route::get('/cart', 'front\CartController@index');
Route::post('/cart', 'front\CartController@store')->name('cart');
Route::get('/cart/save/{id}', 'front\CartController@save')->name('cart.save');
Route::delete('/cart/destroy/{id}', 'front\CartController@destroy')->name('cart.destroy');

//Save Later Route
Route::get('/savelater/move/{id}', 'front\SaveLaterController@move')->name('savelater.move');
Route::delete('/savelater/destroy/{id}', 'front\SaveLaterController@destroy')->name('savelater.destroy');


Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function () {
    //Check Out Route
    Route::get('/checkout', 'front\CheckoutController@index');
    Route::post('/checkout/charge', 'front\CheckoutController@store')->name('checkout');
});

resources/views/admin/sizes/create.blade.php
@extends('admin.layouts.master_layout')

@section('page')
    Add Size
@endsection

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-10 col-md-10">
                    @include('admin.layouts.message')
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Add Size</h4>
                        </div>
                        <div class="content">
                        {!! Form::open(['url' => 'admin/size']) !!}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group {!! $errors->has('name')? 'has-error' : '' !!}">
                                    {!! Form::Label('name','Size Name:') !!}
                                    {!! Form::text('name',old('name'),['class'=>'form-control border-input','placeholder'=>'XXL']) !!}
                                    <span class="text-danger">{!! $errors->has('name')? $errors->first('name') : ''!!}</span>
                                </div>
                                
                            </div>
                            <div class="">
                                {!! Form::submit('Add size',['class'=>'btn btn-info btn-fill btn-wd']) !!}
                            </div>
                            <div class="clearfix"></div>
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/sizes/details.blade.php
@extends('admin.layouts.master_layout')

@section('page')
    Deatils
@endsection

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">

                <div class="col-md-12">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Size Detail</h4>
                            <p class="size">List of all stock</p>
                        </div>
                        <div class="content table-responsive table-full-width">
                            <table class="table table-striped">
                                <tbody>

                                <tr>
                                    <th>ID</th>
                                    <td>{!! $size->id !!}</td>
                                </tr>

                                <tr>
                                    <th>Name</th>
                                    <td>{!! $size->name !!}</td>
                                </tr>

                                <tr>
                                    <th>Created At</th>
                                    <td>{!! $size->created_at->diffForHumans() !!}</td>
                                </tr>

                                <tr>
                                    <th>Updated At</th>
                                    <td>{!! $size->created_at->diffForHumans() !!}</td>
                                </tr>
                                </tbody>

                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/sizes/edit.blade.php
@extends('admin.layouts.master_layout')

@section('page')
    Edit Size
@endsection

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-10 col-md-10">
                    @include('admin.layouts.message')
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Edit Size</h4>
                        </div>
                        <div class="content">
                            {!! Form::open(['url' => ['admin/size',$size->id],'method'=>'put']) !!}
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group {!! $errors->has('name')? 'has-error' : '' !!}">
                                        {!! Form::Label('name','Size Name:') !!}
                                        {!! Form::text('name',$size->name,['class'=>'form-control border-input','placeholder'=>'XL']) !!}
                                        <span class="text-danger">{!! $errors->has('name')? $errors->first('name') : ''!!}</span>
                                    </div> 
                                </div>
                                <div class="">
                                    {!! Form::submit('update size',['class'=>'btn btn-info btn-fill btn-wd']) !!}
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/sizes/index.blade.php
@extends('admin.layouts.master_layout')

@section('page')
    View Sizes
@endsection

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    @include('admin.layouts.message')
                    <div class="card row">
                        <div class="header col-md-2">
                            <h4 class="title">All Sizes</h4>
                            <p class="size">List of all stock</p>
                        </div>
                        <div class="col-md-4" style="margin-top:20px">
                        <a href="{{route('size.create')}}" class="btn btn-info   btn-wd'">Add<i class="fa fa-plus"></i></a>
                        </div>
                        <div class="content table-responsive table-center ">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Created At</th>
                                    <th>Updated At</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($sizes as $index=>$size)
                                <tr>
                                    <td>{!! $size->id !!}</td>
                                    <td>{!! $size->name !!}</td>
                                    <td>{!! $size->created_at->diffForHumans() !!}</td>
                                    <td>{!! $size->updated_at->diffForHumans() !!}</td>
                                    <td>
                                        {!! Form::open(['route'=>['size.destroy',$size->id],'method'=>'DELETE']) !!}
                                            {!! Form::button('<span class="ti-trash"></span>',['type'=>'submit','class'=>'btn btn-sm btn-danger','onclick'=>'return confirm("You Sure To Delete This")']) !!}
                                            {!! link_to_route('size.edit','',$size->id,['class'=>"btn btn-sm btn-info ti-pencil-alt"]) !!}
                                            {!! link_to_route('size.show','',$size->id,['class'=>"btn btn-sm btn-primary ti-view-list-alt"]) !!}
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection