routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
 * Admin Route
*/

Route::prefix('admin')->group(function () {
    Route::middleware('auth:admin')->group(function () {
        //dashboard route
        Route::get('/', 'dashboardController@index');

        //Product route
        Route::resource('/product', 'ProductController');

        //Billings route
        Route::resource('/billings', 'BillingController');
        Route::get('/confirm/{id}', 'BillingController@confirm')->name('orders.confirm');
        Route::get('/pending/{id}', 'BillingController@pending')->name('orders.pending');
        //Category route
        Route::resource('/category', 'CategoryController');

        //Color route
        Route::resource('/color', 'ColorController');

        //Size route
        Route::resource('/size', 'SizeController');

        //feedbacks route
        Route::resource('/feedbacks', 'FeedbackController');


        //Order route
        Route::resource('/orders', 'OrderController');
        Route::get('/confirm/{id}', 'OrderController@confirm')->name('orders.confirm');
        Route::get('/pending/{id}', 'OrderController@pending')->name('orders.pending');

        //User route
        Route::resource('/users', 'UserController');
        Route::get('/active/{id}', 'UserController@active')->name('users.active');
        Route::get('/block/{id}', 'UserController@block')->name('users.block');

        //logout Route
        Route::get('/logout', 'AdminUserController@logout');
    });
    //Admin route
    Route::resource('/login', 'AdminUserController');
});

/* Front-end Route */

//Home Route
Route::resource('/', 'front\HomeController');

//User Rgestrition Route
Route::get('/user/register', 'front\RegisterController@index');
Route::post('/user/register', 'front\RegisterController@store');

//User Login Route
Route::get('/user/login', 'front\SessionController@index');
Route::post('/user/login', 'front\SessionController@store');
Route::get('/logout', 'front\SessionController@logout');


//User Profile Route
Route::get('/user/profile', 'front\UserProfileController@index');
Route::get('/user/order/{id}', 'front\UserProfileController@show');

//Product Profile Route
Route::get('/product/{id}', 'front\ProductController@index');

//Cart Route
Route::get('/cart', 'front\CartController@index');
Route::post('/cart', 'front\CartController@store')->name('cart');
Route::get('/cart/save/{id}', 'front\CartController@save')->name('cart.save');
Route::delete('/cart/destroy/{id}', 'front\CartController@destroy')->name('cart.destroy');

//Save Later Route
Route::get('/savelater/move/{id}', 'front\SaveLaterController@move')->name('savelater.move');
Route::delete('/savelater/destroy/{id}', 'front\SaveLaterController@destroy')->name('savelater.destroy');


Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function () {
    //Check Out Route
    Route::get('/checkout', 'front\CheckoutController@index');
    Route::post('/checkout/charge', 'front\CheckoutController@store')->name('checkout');
});

app/Color.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Color extends Model
{
    protected $fillable = ['name', 'color'];
}

app/Http/Controllers/ColorController.php
<?php

namespace App\Http\Controllers;

use App\Color;
use Illuminate\Validation\Rule;
use Illuminate\Http\Request;

class ColorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $colors  = Color::all();
        return view('admin.colors.index', compact('colors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.colors.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'        => 'required|unique:colors',
            'color'      => 'required'
        ]);

        Color::create($request->all());
        session()->flash('msg', 'Your Color has been Added');
        return redirect(route('color.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Color  $color
     * @return \Illuminate\Http\Response
     */
    public function show(Color $color)
    {
        return view('admin.colors.details', compact('color'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Color  $color
     * @return \Illuminate\Http\Response
     */
    public function edit(Color $color)
    {
        return view('admin.colors.edit', compact('color'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Color  $color
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Color $color)
    {
        $request->validate([
            'name' => ['required', Rule::unique('colors')->ignore($color->id),],
            'color' => 'sometimes|nullable'
        ]);

        $color->update($request->all());

        session()->flash('msg', 'Your Color has been Updated');
        return redirect('/admin/color');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Color  $color
     * @return \Illuminate\Http\Response
     */
    public function destroy(Color $color)
    {
        $color->delete();
        session()->flash('msg', 'Your Color has been deleted');
        return redirect('/admin/color');
    }
}

resources/views/admin/colors/create.blade.php
@extends('admin.layouts.master_layout')

@section('page')
    Add Color
@endsection

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-10 col-md-10">
                    @include('admin.layouts.message')
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Add Color</h4>
                        </div>
                        <div class="content">
                        {!! Form::open(['url' => 'admin/color']) !!}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group {!! $errors->has('name')? 'has-error' : '' !!}">
                                    {!! Form::Label('name','Color Name:') !!}
                                    {!! Form::text('name',old('name'),['class'=>'form-control border-input','placeholder'=>'red']) !!}
                                    <span class="text-danger">{!! $errors->has('name')? $errors->first('name') : ''!!}</span>
                                </div>

                                <div class="form-group  {!! $errors->has('color')? 'has-error' : '' !!}">
                                    {!! Form::Label('color','Color Code:') !!}
                                    {!! Form::color('color',old('descritpion'),['class'=>'form-control border-input']) !!}
                                    <span class="text-danger">{!! $errors->has('color')? $errors->first('color') : ''!!}</span>
                                </div>
                                
                            </div>
                            <div class="">
                                {!! Form::submit('Add Color',['class'=>'btn btn-info btn-fill btn-wd']) !!}
                            </div>
                            <div class="clearfix"></div>
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/colors/details.blade.php
@extends('admin.layouts.master_layout')

@section('page')
    Deatils
@endsection

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">

                <div class="col-md-12">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Color Detail</h4>
                            <p class="color">List of all stock</p>
                        </div>
                        <div class="content table-responsive table-full-width">
                            <table class="table table-striped">
                                <tbody>

                                <tr>
                                    <th>ID</th>
                                    <td>{!! $color->id !!}</td>
                                </tr>

                                <tr>
                                    <th>Name</th>
                                    <td>{!! $color->name !!}</td>
                                </tr>

                                <tr>
                                    <th>Color Code</th>
                                    <td>
                                        <div style="width: 60px; height:60px; border:0.1px solid #888; background-color:{{$color->color}} !important;"></div>
                                    </td>
                                </tr>

                                <tr>
                                    <th>Created At</th>
                                    <td>{!! $color->created_at->diffForHumans() !!}</td>
                                </tr>

                                <tr>
                                    <th>Updated At</th>
                                    <td>{!! $color->updated_at->diffForHumans() !!}</td>
                                </tr>
                                </tbody>

                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/colors/edit.blade.php
@extends('admin.layouts.master_layout')

@section('page')
    Edit Color
@endsection

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-10 col-md-10">
                    @include('admin.layouts.message')
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Edit color</h4>
                        </div>
                        <div class="content">
                            {!! Form::open(['url' => ['admin/color',$color->id],'method'=>'put']) !!}
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group {!! $errors->has('name')? 'has-error' : '' !!}">
                                        {!! Form::Label('name','color Name:') !!}
                                        {!! Form::text('name',$color->name,['class'=>'form-control border-input','placeholder'=>'red']) !!}
                                        <span class="text-danger">{!! $errors->has('name')? $errors->first('name') : ''!!}</span>
                                    </div>

                                    <div class="form-group  {!! $errors->has('color')? 'has-error' : '' !!}">
                                        {!! Form::Label('color','Color Code:') !!}
                                        {!! Form::color('color',$color->color,['class'=>'form-control border-input']) !!}
                                        <span class="text-danger">{!! $errors->has('color')? $errors->first('color') : ''!!}</span>
                                    </div>                                
                                    
                                </div>
                                <div class="">
                                    {!! Form::submit('update color',['class'=>'btn btn-info btn-fill btn-wd']) !!}
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/colors/index.blade.php
@extends('admin.layouts.master_layout')

@section('page')
    View Colors
@endsection

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    @include('admin.layouts.message')
                    <div class="card row">
                        <div class="header col-md-2">
                            <h4 class="title">All Colors</h4>
                            <p class="color">List of all stock</p>
                        </div>
                        <div class="col-md-4" style="margin-top:20px">
                            <a href="{{route('color.create')}}" class="btn btn-info   btn-wd'">Add<i class="fa fa-plus"></i></a>
                        </div>
                        <div class="content table-responsive table-center ">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Color</th>
                                    <th>Created At</th>
                                    <th>Updated At</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($colors as $index=>$color)
                                <tr>
                                    <td>{!! $index+1 !!}</td>
                                    <td>{!! $color->name !!}</td>
                                    <td>
                                        <div style="width: 30px; height:30px; border:0.1px solid #888; background-color:{{$color->color}} !important;"></div>
                                    </td>
                                    <td>{!! $color->created_at->diffForHumans() !!}</td>
                                    <td>{!! $color->updated_at->diffForHumans() !!}</td>
                                    <td>
                                        {!! Form::open(['route'=>['color.destroy',$color->id],'method'=>'DELETE']) !!}
                                            {!! Form::button('<span class="ti-trash"></span>',['type'=>'submit','class'=>'btn btn-sm btn-danger','onclick'=>'return confirm("You Sure To Delete This")']) !!}
                                            {!! link_to_route('color.edit','',$color->id,['class'=>"btn btn-sm btn-info ti-pencil-alt"]) !!}
                                            {!! link_to_route('color.show','',$color->id,['class'=>"btn btn-sm btn-primary ti-view-list-alt"]) !!}
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection