routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
 * Admin Route
*/

Route::prefix('admin')->group(function () {
    Route::middleware('auth:admin')->group(function () {
        //dashboard route
        Route::get('/', 'dashboardController@index');

        //Product route
        Route::resource('/product', 'ProductController');

        //Billings route
        Route::resource('/billings', 'BillingController');
        Route::get('/confirm/{id}', 'BillingController@confirm')->name('orders.confirm');
        Route::get('/pending/{id}', 'BillingController@pending')->name('orders.pending');
        //Category route
        Route::resource('/category', 'CategoryController');

        //Color route
        Route::resource('/color', 'ColorController');

        //Size route
        Route::resource('/size', 'SizeController');

        //feedbacks route
        Route::resource('/feedbacks', 'FeedbackController');


        //Order route
        Route::resource('/orders', 'OrderController');
        Route::get('/confirm/{id}', 'OrderController@confirm')->name('orders.confirm');
        Route::get('/pending/{id}', 'OrderController@pending')->name('orders.pending');

        //User route
        Route::resource('/users', 'UserController');
        Route::get('/active/{id}', 'UserController@active')->name('users.active');
        Route::get('/block/{id}', 'UserController@block')->name('users.block');

        //logout Route
        Route::get('/logout', 'AdminUserController@logout');
    });
    //Admin route
    Route::resource('/login', 'AdminUserController');
});

/* Front-end Route */

//Home Route
Route::resource('/', 'front\HomeController');

//User Rgestrition Route
Route::get('/user/register', 'front\RegisterController@index');
Route::post('/user/register', 'front\RegisterController@store');

//User Login Route
Route::get('/user/login', 'front\SessionController@index');
Route::post('/user/login', 'front\SessionController@store');
Route::get('/logout', 'front\SessionController@logout');


//User Profile Route
Route::get('/user/profile', 'front\UserProfileController@index');
Route::get('/user/order/{id}', 'front\UserProfileController@show');

//Product Profile Route
Route::get('/product/{id}', 'front\ProductController@index');

//Cart Route
Route::get('/cart', 'front\CartController@index');
Route::post('/cart', 'front\CartController@store')->name('cart');
Route::get('/cart/save/{id}', 'front\CartController@save')->name('cart.save');
Route::delete('/cart/destroy/{id}', 'front\CartController@destroy')->name('cart.destroy');

//Save Later Route
Route::get('/savelater/move/{id}', 'front\SaveLaterController@move')->name('savelater.move');
Route::delete('/savelater/destroy/{id}', 'front\SaveLaterController@destroy')->name('savelater.destroy');


Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function () {
    //Check Out Route
    Route::get('/checkout', 'front\CheckoutController@index');
    Route::post('/checkout/charge', 'front\CheckoutController@store')->name('checkout');
});

app/Billing.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Billing extends Model
{

    protected $fillable = [
        'name',
        'email',
        'address',
        'city',
        'province',
        'postal',
        'phone',
        'user_id',
    ];

    public function order()
    {
        return $this->hasOne(Order::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'first_name', 'last_name', 'email', 'password', 'image', 'birth_date', 'status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    public function order()
    {
        return $this->hasMany(Order::class);
    }

    public function getfullnameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }
}

app/Http/Controllers/BillingController.php
<?php

namespace App\Http\Controllers;

use App\Order;

use App\Billing;
use Illuminate\Http\Request;

class BillingController extends Controller
{
    public function index()
    {
        $billings = Billing::all();
        return view('admin.billings.index', compact('billings'));
    }

    public function confirm($id)
    {
        $billing = Billing::find($id);
        $billing->update(['status' => 1]);
        session()->flash('msg', 'billing has been confirmed');
        return redirect('/admin/billings');
    }

    public function pending($id)
    {
        $billing = Billing::find($id);
        $billing->update(['status' => 0]);
        session()->flash('msg', 'billing again has been Pending');
        return redirect('/admin/billings');
    }

    public function show($id)
    {
        $order = Order::find($id);
        $billing = Billing::find($id);
        return view('admin.billings.details', compact('billing', 'order'));
    }


    public function destroy($id)
    {
        Billing::destroy($id);
        session()->flash('msg', 'Your Billing has been deleted');
        return redirect('/admin/billings');
    }
}

resources/views/admin/billings/details.blade.php
@extends('admin.layouts.master_layout')

@section('page')
    Order Details
@endsection

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                 <div class="col-md-12">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Billings Details</h4>
                            <p class="category">Billings Details</p>
                        </div>
                         <div class="content table-responsive table-full-width">
                            <table class="table table-striped"> 
                                    <tr>
                                        <th>Custmor Name</th>
                                        <td>{{ $billing->name }}</td>
                                    </tr>
                                    <tr>
                                        <th>Email</th>
                                        <td>{{ $billing->email }}</td>
                                    </tr>
                                    <tr>
                                        <th>Address</th>
                                        <td>{{ $billing->address }}</td>
                                    </tr>
                                    <tr>
                                        <th>City</th>
                                        <td>{{ $billing->city }}</td>
                                    <tr>
                                        <th>Province</th>
                                        <td>{{ $billing->province }}</td>
                                    </tr>
                                    <tr>
                                        <th>Postal</th>
                                        <td>{{ $billing->postal }}</td>
                                    </tr>
                                    <tr>
                                        <th>Phone</th>
                                        <td>{{ $billing->phone }}</td>
                                    </tr>
                                    <tr>
                                        <th>Date</th>
                                        <td>{{ $billing->created_at->diffForHumans() }}</td>
                                    </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Order Details</h4>
                            <p class="category">Order details</p>
                        </div>
                        <div class="content table-responsive table-full-width">
                            <table class="table table-striped">
                                <tr>
                                    <th>ID</th>
                                    <td>{{ $billing->order->id }}</td>
                                </tr>
                                <tr>
                                    <th>Date</th>
                                    <td>{{ $billing->order->created_at->diffForHumans() }}</td>
                                </tr>
                                <tr>
                                    <th>Product NO</th>
                                    <td>{{ $billing->order->order_item->count() }}</td>
                                </tr>
                                <tr>
                                    <th>Status</th>
                                    <td>
                                        @if ($billing->order->status)
                                            <span class="label label-success">Confirmed</span>
                                        @else
                                            <span class="label label-warning">Pending</span>
                                        @endif
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>  
                  
                <div class="col-md-6">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">User Details</h4>
                            <p class="category">User Details</p>
                        </div>
                        <div class="content table-responsive table-full-width">
                            <table class="table table-striped">
                               
                                <tr>
                                    <th>Name</th>
                                    <td>{{ $order->user->fullname }}</td>
                                </tr>
                                <tr>
                                    <th>Email</th>
                                    <td>{{ $order->user->email }}</td>
                                </tr>                                
                                <tr>
                                    <th>Image</th>
                                    <td><img src={!! url("uploads/users").'/'.$order->user->image !!} alt = {!! $order->user->image!!} class="img-thumbnail" style="width: 100px"></td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">product_item Details</h4>
                            <p class="category">product_item Details</p>
                        </div>
                        <div class="content table-responsive table-full-width">
                             <table class="table table-striped">
                                <tr>
                                    <th>NO</th>
                                    <th>Name</th>
                                    <th>Category</th>
                                    <th>Color</th>
                                    <th>Size</th>
                                    <th>Qauntity</th>
                                    <th>Price</th>
                                    <th>Image</th>
                                </tr>
                                <tbody>
                             
                                @foreach($order->order_item as $index=>$product_item )  
                                <tr>
                                    <td>{!! $index+1!!}</td>
                                    <td>{!! $product_item->product->name!!}</td>
                                    <td>{!! $product_item->product->category->name!!}</td> 
                                    <td><div style="width: 20px; height:20px; border:0.1px solid #888; display:inline-block; background-color:{!! $product_item->product_color !!}!important;"></div></td>
                                    <td>{!! $product_item->product_size!!}</td>
                                    <td>{!! $product_item->quainty!!}</td>
                                    <td>{!! $product_item->price !!}$</td>
                                    <td><img src={!! url("uploads/products").'/'.$product_item->product->image !!} alt={!! $product_item->product->image!!} class="img-thumbnail" style="width: 50px"></td>
                                </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <a href="{{ url('/admin/billings') }}" class="btn btn-success">Back to Billings</a>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/billings/index.blade.php
@extends('admin.layouts.master_layout')

@section('page')
    View Billings
@endsection

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    @include('admin.layouts.message')
                    <div class="card">
                        <div class="header col-md-2">
                            <h4 class="title">All Billings</h4>
                            <p class="product">List of all stock</p>
                        </div>
                      
                        <div class="content table-responsive table-full-width">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>NO</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>province</th>
                                    <th>Phone</th>
                                    <th>Date</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($billings as $index=>$billing)
                                    @if ($billing->order->status)  
                                    <tr>
                                        
                                        <td>{!! $index+1 !!}</td>
                                        <td>{!! $billing->name!!}</td>
                                        <td>{!! $billing->email!!}</td>
                                        <td>{!! $billing->province!!}</td>
                                        <td>{!! $billing->phone!!}</td>
                                        <td>{!! $billing->created_at->diffForHumans()!!}</td>
                                        <td>
                                            {!! Form::open(['route'=>['billings.destroy',$billing->id],'method'=>'DELETE']) !!}
                                                {!! Form::button('<span class="ti-trash"></span>',['type'=>'submit','class'=>'btn btn-sm btn-danger','onclick'=>'return confirm("You Sure To Delete This")']) !!}
                                            
                                                {!! link_to_route('billings.show','',$billing->id,['class'=>"btn btn-sm btn-primary ti-view-list-alt"]) !!}
                                            {!! Form::close() !!}
                                        </td>
                                    </tr>                               
                                    @endif
                                @endforeach 
                                
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection