routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
 * Admin Route
*/

Route::prefix('admin')->group(function () {
    Route::middleware('auth:admin')->group(function () {
        //dashboard route
        Route::get('/', 'dashboardController@index');

        //Product route
        Route::resource('/product', 'ProductController');

        //Billings route
        Route::resource('/billings', 'BillingController');
        Route::get('/confirm/{id}', 'BillingController@confirm')->name('orders.confirm');
        Route::get('/pending/{id}', 'BillingController@pending')->name('orders.pending');
        //Category route
        Route::resource('/category', 'CategoryController');

        //Color route
        Route::resource('/color', 'ColorController');

        //Size route
        Route::resource('/size', 'SizeController');

        //feedbacks route
        Route::resource('/feedbacks', 'FeedbackController');


        //Order route
        Route::resource('/orders', 'OrderController');
        Route::get('/confirm/{id}', 'OrderController@confirm')->name('orders.confirm');
        Route::get('/pending/{id}', 'OrderController@pending')->name('orders.pending');

        //User route
        Route::resource('/users', 'UserController');
        Route::get('/active/{id}', 'UserController@active')->name('users.active');
        Route::get('/block/{id}', 'UserController@block')->name('users.block');

        //logout Route
        Route::get('/logout', 'AdminUserController@logout');
    });
    //Admin route
    Route::resource('/login', 'AdminUserController');
});

/* Front-end Route */

//Home Route
Route::resource('/', 'front\HomeController');

//User Rgestrition Route
Route::get('/user/register', 'front\RegisterController@index');
Route::post('/user/register', 'front\RegisterController@store');

//User Login Route
Route::get('/user/login', 'front\SessionController@index');
Route::post('/user/login', 'front\SessionController@store');
Route::get('/logout', 'front\SessionController@logout');


//User Profile Route
Route::get('/user/profile', 'front\UserProfileController@index');
Route::get('/user/order/{id}', 'front\UserProfileController@show');

//Product Profile Route
Route::get('/product/{id}', 'front\ProductController@index');

//Cart Route
Route::get('/cart', 'front\CartController@index');
Route::post('/cart', 'front\CartController@store')->name('cart');
Route::get('/cart/save/{id}', 'front\CartController@save')->name('cart.save');
Route::delete('/cart/destroy/{id}', 'front\CartController@destroy')->name('cart.destroy');

//Save Later Route
Route::get('/savelater/move/{id}', 'front\SaveLaterController@move')->name('savelater.move');
Route::delete('/savelater/destroy/{id}', 'front\SaveLaterController@destroy')->name('savelater.destroy');


Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function () {
    //Check Out Route
    Route::get('/checkout', 'front\CheckoutController@index');
    Route::post('/checkout/charge', 'front\CheckoutController@store')->name('checkout');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'description'];

    public function products()
    {

        return $this->hasMany('\App\Product', 'cat_id', 'id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Validation\Rule;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories  = Category::all();
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.add_category');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'        => 'required|unique:categories',
            'description' => 'smoetimes|nullable'
        ]);

        $data = $request->except(['desritpion']);

        if ($request->description == '') {
            $data['description'] = 'This Category Not Contain Desription';
        }
        Category::create($data);
        session()->flash('msg', 'Your Category has been Added');
        return redirect(route('category.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('admin.categories.details', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $request->validate([
            'name' => ['required', Rule::unique('categories')->ignore($category->id),],
            'description' => 'sometimes|nullable'
        ]);

        $data = $request->except(['desritpion']);

        if ($request->description == '') {
            $data['description'] = 'This Category Not Contain Desription';
        }

        $category->update($data);

        session()->flash('msg', 'Your Category has been Updated');
        return redirect('/admin/category');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        session()->flash('msg', 'Your Category has been deleted');
        return redirect('/admin/category');
    }
}

resources/views/admin/categories/add_category.blade.php
@extends('admin.layouts.master_layout')

@section('page')
    Add Category
@endsection

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-10 col-md-10">
                    @include('admin.layouts.message')
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Add Category</h4>
                        </div>
                        <div class="content">
                        {!! Form::open(['url' => 'admin/category']) !!}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group {!! $errors->has('name')? 'has-error' : '' !!}">
                                    {!! Form::Label('name','Category Name:') !!}
                                    {!! Form::text('name',old('name'),['class'=>'form-control border-input','placeholder'=>'Main Category']) !!}
                                    <span class="text-danger">{!! $errors->has('name')? $errors->first('name') : ''!!}</span>
                                </div>

                                <div class="form-group  {!! $errors->has('description')? 'has-error' : '' !!}">
                                    {!! Form::Label('description','Category description:') !!}
                                    {!! Form::textarea('description',old('descritpion'),['class'=>'form-control border-input','placeholder'=>'Category Decription']) !!}
                                    <span class="text-danger">{!! $errors->has('description')? $errors->first('description') : ''!!}</span>
                                </div>
                                
                            </div>
                            <div class="">
                                {!! Form::submit('Add Caregory',['class'=>'btn btn-info btn-fill btn-wd']) !!}
                            </div>
                            <div class="clearfix"></div>
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/details.blade.php
@extends('admin.layouts.master_layout')

@section('page')
    Deatils
@endsection

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">

                <div class="col-md-12">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">category Detail</h4>
                            <p class="category">List of all stock</p>
                        </div>
                        <div class="content table-responsive table-full-width">
                            <table class="table table-striped">
                                <tbody>

                                <tr>
                                    <th>ID</th>
                                    <td>{!! $category->id !!}</td>
                                </tr>

                                <tr>
                                    <th>Name</th>
                                    <td>{!! $category->name !!}</td>
                                </tr>

                                <tr>
                                    <th>Description</th>
                                    <td>{!! $category->description !!}</td>
                                </tr>

                                <tr>
                                    <th>Number Of Product</th>
                                    <td>{!! $category->products->count() !!}</td>
                                </tr>

                                <tr>
                                    <th>Created At</th>
                                    <td>{!! $category->created_at->diffForHumans() !!}</td>
                                </tr>

                                <tr>
                                    <th>Updated At</th>
                                    <td>{!! $category->created_at->diffForHumans() !!}</td>
                                </tr>
                                </tbody>

                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.master_layout')

@section('page')
    Edit Categories
@endsection

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-10 col-md-10">
                    @include('admin.layouts.message')
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Edit Category</h4>
                        </div>
                        <div class="content">
                            {!! Form::open(['url' => ['admin/category',$category->id],'method'=>'put']) !!}
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group {!! $errors->has('name')? 'has-error' : '' !!}">
                                        {!! Form::Label('name','category Name:') !!}
                                        {!! Form::text('name',$category->name,['class'=>'form-control border-input','placeholder'=>'MackBook','required'=>'required']) !!}
                                        <span class="text-danger">{!! $errors->has('name')? $errors->first('name') : ''!!}</span>
                                    </div>

                                    <div class="form-group  {!! $errors->has('description')? 'has-error' : '' !!}">
                                        {!! Form::Label('description','Category Description:') !!}
                                        {!! Form::textarea('description',$category->description,['class'=>'form-control border-input','placeholder'=>'category Description','cols'=>'30','rows'=>'7']) !!}
                                        <span class="text-danger">{!! $errors->has('description')? $errors->first('description') : ''!!}</span>
                                    </div>                                
                                    
                                </div>
                                <div class="">
                                    {!! Form::submit('update category',['class'=>'btn btn-info btn-fill btn-wd']) !!}
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.master_layout')

@section('page')
    View Categories
@endsection

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    @include('admin.layouts.message')
                    <div class="card row">
                        <div class="header col-md-2">
                            <h4 class="title">All Categories</h4>
                            <p class="category">List of all stock</p>
                        </div>
                        <div class="col-md-4" style="margin-top:20px">
                        <a href="{{route('category.create')}}" class="btn btn-info   btn-wd'">Add<i class="fa fa-plus"></i></a>
                        </div>
                        <div class="content table-responsive table-center ">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>NO.Product</th>
                                    <th>Desc</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($categories as $index=>$category)
                                <tr>
                                    <td>{!! $category->id !!}</td>
                                    <td>{!! $category->name !!}</td>
                                    <td>{!! $category->products->count()!!}</td>
                                    <td>{!! $category->description !!}</td>
                                    <td>
                                        {!! Form::open(['route'=>['category.destroy',$category->id],'method'=>'DELETE']) !!}
                                            {!! Form::button('<span class="ti-trash"></span>',['type'=>'submit','class'=>'btn btn-sm btn-danger','onclick'=>'return confirm("You Sure To Delete This")']) !!}
                                            {!! link_to_route('category.edit','',$category->id,['class'=>"btn btn-sm btn-info ti-pencil-alt"]) !!}
                                            {!! link_to_route('category.show','',$category->id,['class'=>"btn btn-sm btn-primary ti-view-list-alt"]) !!}
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection